/*----------- USUARIO -----------*/
/*

*/

DELIMITER $$  
CREATE PROCEDURE `sp_USUARIO_C` 
(in NOMBRE VARCHAR (25),IN PW VARCHAR(25),IN IMAGEN MEDIUMBLOB,IN USUARIO VARCHAR(50),IN CORREO VARCHAR(50))
BEGIN
INSERT INTO USUARIO(NOMBRE,PW,AVATAR,USUARIO,CORREO) 
VALUES(NOMBRE,PW,IMAGEN,USUARIO,CORREO);
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE `sp_BuscarUsuario` (IN PW varchar(50),in CORREO VARCHAR (50))
BEGIN
SELECT ID,AVATAR,NOMBRE,USUARIO FROM USUARIO WHERE USUARIO.PW=PW AND USUARIO.CORREO=CORREO;
END
$$
DELIMITER ;

DELIMITER $$
create PROCEDURE `sp_FilterUsuario` (in NAM VARCHAR (50), ID_s int)
BEGIN
SELECT ID, NOMBRE FROM USUARIO WHERE USUARIO.NOMBRE like concat('%',NAM,'%') and ID != ID_s limit 3;
END
$$
DELIMITER ;

DELIMITER ; 

DELIMITER $$
CREATE PROCEDURE `sp_USUARIO_U` (IN ID_s INT,in NOMBRE VARCHAR (25),IN PW VARCHAR(25),IN IMAGEN BLOB,IN USUARIO VARCHAR(50),IN CORREO VARCHAR(50))
BEGIN
update USUARIO set NOMBRE=NOMBRE, PW=PW, IMAGE=IMAGE, CORREO=CORREO, USUARIO=USUARIO where ID= ID_s;
END
$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE `sp_USUARIO_ACTIVO` (IN ID_s INT)
BEGIN
update USUARIO set ACTIVO=1 where ID= ID_s;

select * from USUARIO WHERE ID= ID_s;
END
$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE `sp_USUARIO_INACTIVO` (IN ID_s INT)
BEGIN
update USUARIO set ACTIVO=0, LASTTIME=current_timestamp() where ID= ID_s;
END
$$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE `sp_USUARIO_D` (IN ID_s INT)
BEGIN
update USUARIO set ACTIVO=0 where ID= ID_s;
END
$$
DELIMITER ;


/*----------- EQUIPO -----------*/

DELIMITER $$  
CREATE PROCEDURE `sp_EQUIPO_C` 
(in NOMBRE VARCHAR (50), in CREADOR INT, in IMAGEN mediumblob)
BEGIN
INSERT INTO EQUIPO(NOMBRE, FK_IDCREADOR, IMAGEN) 
VALUES(NOMBRE, CREADOR, IMAGEN);

END $$
DELIMITER ;

DELIMITER $$  
CREATE PROCEDURE `getFotoTeam` 
(in id int)
BEGIN
SELECT IMAGEN FROM EQUIPO where ID= id;

END $$
DELIMITER ;


DELIMITER $$  
CREATE PROCEDURE `sp_EQUIPO_SHOW` 
(in ids int)
BEGIN
SELECT ID, NOMBRE, FK_IDCREADOR as CREADOR FROM EQUIPO WHERE ID = ids limit 1;
END $$
DELIMITER ;


DELIMITER $$  
CREATE PROCEDURE `sp_MIEMBRODEEQUIPO_SHOW` 
(in id int)
BEGIN
SELECT * FROM V_MIEMBRODELEQUIPO where (IDUSUARIO= id) OR (IDCREADOR= id);

END $$
DELIMITER ;

DELIMITER $$  
CREATE PROCEDURE `sp_EQUIPO_SHOWLAST` 
()
BEGIN
SELECT ID, NOMBRE FROM EQUIPO ORDER BY ID DESC LIMIT 1;

END $$
DELIMITER ;

DELIMITER ; 

DELIMITER $$
CREATE PROCEDURE `sp_EQUIPO_U` (IN ID_s INT,in NOMBRE VARCHAR (25))
BEGIN
update USUARIO set NOMBRE=NOMBRE where ID= ID_s;
END
$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE `sp_EQUIPO_D` (IN ID_s INT)
BEGIN
update EQUIPO set ACTIVO=0 where ID= ID_s;
END
$$
DELIMITER ;



DELIMITER $$  
CREATE PROCEDURE `sp_EQUIPOUSUARIOS_C` 
(in Team int, in usuario INT)
BEGIN
INSERT INTO EQUIPOUSUARIOS(FK_IDEQUIPO, FK_IDUSUARIO) 
VALUES(Team, usuario);

END $$
DELIMITER ;


/*----------- MENSAJE -----------*/

DELIMITER $$
CREATE PROCEDURE `sp_MENSAJE_C` (in MENSAJES VARCHAR (500),in ENCRIPTA bool, IN RECEPTOR INT, IN EMISOR INT)
BEGIN
INSERT INTO MENSAJE(MENSAJE,ENCRIPTACION,HORA, FK_IDRECEPTOR, FK_IDEMISSOR) 
VALUES(MENSAJES,ENCRIPTA,NOW(),RECEPTOR ,EMISOR);
END
$$

DELIMITER $$
CREATE PROCEDURE `sp_MENSAJE_CrearFoto` (in MENSAJES VARCHAR (500),in ENCRIPTA bool, IN RECEPTOR INT, IN EMISOR INT,IN FOTO mediumblob,in hayImg bool)
BEGIN
INSERT INTO MENSAJE(MENSAJE,ENCRIPTACION,HORA,IMAGEN, FK_IDRECEPTOR, FK_IDEMISSOR,HAYIMG) 
VALUES(MENSAJES,ENCRIPTA,NOW(),FOTO, RECEPTOR ,EMISOR,hayImg);
END
$$

DELIMITER $$
CREATE PROCEDURE `sp_MENSAJE_U` (IN ID_s INT,in MENSAJE VARCHAR (25),IN HORA TIME, IN VISTO BOOL,IN IMAGEN BLOB)
BEGIN
update MENSAJE set MENSAJE=MENSAJE,HORA=HORA,VISTO=VISTO,IMAGEN=IMAGEN where ID= ID_s;
END
$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE `sp_MENSAJE_CHATS` (IN ID_s INT)
BEGIN
SELECT * FROM V_CHATS WHERE EMISSOR_ID = ID_s OR RECEPTOR_ID = ID_s;
END
$$
DELIMITER ;



DELIMITER $$
CREATE PROCEDURE `sp_MENSAJE_D` (IN ID_s INT)
BEGIN
update MENSAJE set ACTIVO=0 where ID= ID_s;
END
$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE `sp_MENSAJE_SHOW` (IN EMID INT, IN REID INT)
BEGIN
select * from V_MENSAJES WHERE (EMISSOR_ID = EMID  AND RECEPTOR_ID = REID) OR(EMISSOR_ID = REID  AND RECEPTOR_ID = EMID) ORDER BY HORA asc;

END
$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE `SP_getFotoMsg` (IN ID_Msg INT)
BEGIN
SELECT IMAGEN FROM MENSAJE where ID= ID_Msg;
END
$$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE `sp_MENSAJE_VIEW` (IN EMID INT, IN REID INT)
BEGIN

UPDATE mensaje
SET VISTO = 1
WHERE FK_IDRECEPTOR = REID AND FK_IDEMISSOR = EMID;
END
$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE `sp_MENSAJE_PENDING` (IN REID INT, IN EMID INT)
BEGIN
SELECT SUM(IF(VISTO <> 0, 0, 1)) AS PENDING FROM mensaje WHERE FK_IDRECEPTOR = REID AND FK_IDEMISSOR = EMID;

END
$$
DELIMITER ;


/*----------- PUBLICACION -----------*/

DELIMITER $$  
CREATE PROCEDURE `sp_PUBLICACIONES_C` 
(IN PUBLICACION VARCHAR(500),IN IMAGE BLOB, in EQUIPO INT, IN CREADOR INT)
BEGIN
INSERT INTO PUBLICACIONES(PUBLICACION,IMAGE,HORA, EQUIPO, FK_IDCREADOR) 
VALUES(PUBLICACION,IMAGE,NOW(), EQUIPO, CREADOR);
END $$
DELIMITER ;

DELIMITER ; 

DELIMITER $$
CREATE PROCEDURE `sp_PUBLICACIONES_U` (IN PUBLICACION VARCHAR(500),IN IMAGE BLOB,IN HORA time)
BEGIN
update PUBLICACIONES set PUBLICACION=PUBLICACION,IMAGE=IMAGE,HORA=HORA where ID= ID_s;
END
$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE `sp_PUBLICACIONES_D` (IN ID_s INT)
BEGIN
update PUBLICACIONES set ACTIVO=0 where ID= ID_s;
END
$$
DELIMITER ;

DELIMITER $$  
CREATE PROCEDURE `sp_PUBLICACIONES_SHOWLAST` 
()
BEGIN
select * from PUBLICACIONES ORDER BY ID DESC LIMIT 1;

END $$
DELIMITER ;

DELIMITER $$  
CREATE PROCEDURE `sp_PUBLICACIONES_SHOWALL` 
(IN TEAM INT)
BEGIN
select * from V_PUBLICACIONES_SHOWALLINFO WHERE EQUIPO = TEAM ORDER BY HORA asc;

END $$
DELIMITER ;

/*----------- TAREAS -----------*/

DELIMITER $$  
CREATE PROCEDURE `sp_TAREAS_C` 
(IN TAREA VARCHAR(150),IN CREADOR INT, IN EQUIPO INT, in DESCRIPCION VARCHAR(500))
BEGIN
INSERT INTO TAREAS(TAREA, DESCRIPCION, FK_IDCREADOR, FK_IDEQUIPO) 
VALUES(TAREA,DESCRIPCION, CREADOR, EQUIPO);
END $$
DELIMITER ;

DELIMITER $$  
CREATE PROCEDURE `sp_TAREAS_SHOW` 
(IN AL int)
BEGIN
select * from V_TAREAS WHERE ALUMNO = AL;
END $$
DELIMITER ;

DELIMITER $$  
CREATE PROCEDURE `sp_TAREAS_SHOW_TAR` 
(IN AL int, IN TAR int)
BEGIN
select * from V_TAREAS WHERE ALUMNO = AL AND IDTAREA = TAR;
END $$
DELIMITER ;

DELIMITER $$  
CREATE PROCEDURE `sp_TAREAS_COM` 
(IN TAREA INT,IN USUARIO INT, IN COMPLETE BOOL)
BEGIN

UPDATE USUARIOTAREA
SET COMPLETADO = COMPLETE
WHERE (FK_IDTAREA = TAREA)AND(FK_IDALUMNO = USUARIO);

END $$
DELIMITER ;

DELIMITER $$  
CREATE PROCEDURE `sp_TAREAARCHIVO_C` 
(IN TAREA INT ,IN ARCHIVO longblob, TIPO VARCHAR(20))
BEGIN
INSERT INTO TAREAARCHIVO(FK_IDTAREA, ARCHIVO, TIPO) 
VALUES(TAREA,ARCHIVO, TIPO);
END $$
DELIMITER ;


DELIMITER $$  
CREATE TRIGGER `tg_TAREAS` AFTER INSERT ON TAREAS FOR EACH ROW
BEGIN

INSERT INTO USUARIOTAREA(FK_IDEQUIPOs, FK_IDALUMNO)
SELECT IDEQUIPO, IDUSUARIO FROM V_MIEMBRODELEQUIPO 
WHERE IDEQUIPO = NEW.FK_IDEQUIPO;


UPDATE USUARIOTAREA SET FK_IDTAREA = NEW.ID WHERE (FK_IDEQUIPOs = NEW.FK_IDEQUIPO)and(FK_IDTAREA IS NULL);


END $$
DELIMITER ;


