/*----------- USUARIO -----------*/

DELIMITER $$  
CREATE PROCEDURE `sp_USUARIO_C` 
(in NOMBRE VARCHAR (25),IN PW VARCHAR(25))
BEGIN
INSERT INTO USUARIO(NOMBRE,PW) 
VALUES(NOMBRE,PW);
END $$
DELIMITER ;

DELIMITER ; 

DELIMITER $$
CREATE PROCEDURE `sp_SECCION_U` (IN ID_s INT,in NOMBRE VARCHAR (25),IN PW VARCHAR(25))
BEGIN
update USUARIO set NOMBRE=NOMBRE, PW=PW where ID= ID_s;
END
$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE `sp_SECCION_D` (IN ID_s)
BEGIN
DELETE USUARIO  where ID = ID_s;
END
$$
DELIMITER ;
/*----------- USUARIO -----------*/
