drop database POI;
create database POI;
Use  POI;

create table USUARIO(
ID	INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
AVATAR MEDIUMBLOB,
NOMBRE varchar(50),
USUARIO VARCHAR (50), 
CORREO VARCHAR(50),
PW varchar(25),
ACTIVO BOOL DEFAULT 1, 
LASTTIME datetime
);

CREATE table EQUIPO(
ID	INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOMBRE varchar(50),
IMAGEN MEDIUMBLOB,
ACTIVO BOOL DEFAULT 1

);

create table EQUIPOUSUARIOS(
ID	INT PRIMARY KEY NOT NULL AUTO_INCREMENT

);

Create table PUBLICACIONES(
ID	INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
PUBLICACION VARCHAR(500),
IMAGE BLOB,
HORA time,
EQUIPO int,
ACTIVO BOOL DEFAULT 1
);


Create table REGISTROLLAMADAS(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
DURACION TIME
);

Create table MENSAJE(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
MENSAJE VARCHAR(500),
HORA datetime,
VISTO BOOL default 0,
ENCRIPTACION BOOL default 0,
HAYIMG BOOL default 0,
IMAGEN mediumblob default null
);

CREATE table TAREAS(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
TAREA VARCHAR(150),
DESCRIPCION VARCHAR(500)
);

CREATE TABLE USUARIOTAREA(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
COMPLETADO BOOL default 0
);

CREATE TABLE TAREAARCHIVO(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ARCHIVO LONGBLOB, 
TIPO VARCHAR(20)
);

/*
tabla

name
mediumblob
type

fk tarea

*/

ALTER TABLE MENSAJE MODIFY COLUMN IMAGEN mediumblob default null;

ALTER TABLE EQUIPO
ADD FK_IDCREADOR INT,
ADD foreign key (FK_IDCREADOR) REFERENCES USUARIO(ID);

ALTER TABLE EQUIPOUSUARIOS
ADD FK_IDUSUARIO INT,
ADD foreign key (FK_IDUSUARIO) REFERENCES USUARIO(ID), 
ADD FK_IDEQUIPO INT,
ADD foreign key (FK_IDEQUIPO) REFERENCES EQUIPO(ID);

ALTER TABLE PUBLICACIONES
ADD FK_IDCREADOR INT, 
ADD foreign key (FK_IDCREADOR) REFERENCES USUARIO(ID);

ALTER TABLE MENSAJE
ADD FK_IDRECEPTOR INT, 
ADD foreign key (FK_IDRECEPTOR) REFERENCES USUARIO(ID), 
ADD FK_IDEMISSOR INT, 
ADD foreign key (FK_IDEMISSOR) REFERENCES USUARIO(ID);

ALTER TABLE TAREAS
ADD FK_IDCREADOR INT, 
ADD foreign key (FK_IDCREADOR) REFERENCES USUARIO(ID),
ADD FK_IDEQUIPO INT, 
ADD foreign key (FK_IDEQUIPO) REFERENCES EQUIPO(ID);

ALTER TABLE USUARIOTAREA
ADD FK_IDALUMNO INT,
ADD foreign key (FK_IDALUMNO) REFERENCES USUARIO(ID),
ADD FK_IDTAREA INT,
ADD foreign key (FK_IDTAREA) REFERENCES TAREAS(ID),
ADD FK_IDEQUIPOs INT,
ADD foreign key (FK_IDEQUIPOs) REFERENCES EQUIPO(ID);

ALTER TABLE TAREAARCHIVO
ADD FK_IDTAREA INT,
ADD foreign key (FK_IDTAREA) REFERENCES TAREAS(ID)


