/* VISTAS */

/**********************************************************************/
CREATE VIEW V_USUARIO_EN_EQUIPO AS
	Select U.ID 
	from EQUIPOUSUARIOS E
    INNER join USUARIO u ON U.ID=E.FK_IDUSUARIO/*FK*/
    INNER join EQUIPO EQ ON EQ.ID=E.FK_IDEQUIPO/*FK*/;
/**********************************************************************/
    CREATE VIEW V_PUBLICACIONES AS
	Select P.ID 
	from EQUIPOPUBLICACIONES P
    INNER join PUBLICACIONES PU ON P.FK_IDPUBLICACION=PU.ID;
/**********************************************************************/
CREATE VIEW V_MENSAJES AS
	Select M.ID as IdMsg, M.FK_IDEMISSOR AS EMISSOR_ID,M.FK_IDRECEPTOR AS RECEPTOR_ID, IDRECEPTOR.NOMBRE AS NOMBRE_RECEPTOR,M.MENSAJE,M.HORA,  IDRECEPTOR.ACTIVO, IDRECEPTOR.LASTTIME,
			M.ENCRIPTACION,M.IMAGEN, M.HAYIMG 
	from  MENSAJE M
    INNER JOIN USUARIO IDEMISSOR ON M.FK_IDEMISSOR= IDEMISSOR.ID
	INNER JOIN USUARIO IDRECEPTOR ON M.FK_IDRECEPTOR = IDRECEPTOR.ID;

    /**********************************************************************/
CREATE VIEW V_CHATS AS
	Select DISTINCT M.FK_IDRECEPTOR AS RECEPTOR_ID, IDRECEPTOR.NOMBRE AS NOMBRE_RECEPTOR, M.FK_IDEMISSOR AS EMISSOR_ID, IDEMISSOR.NOMBRE AS NOMBRE_EMISOR,  IDRECEPTOR.ACTIVO, IDRECEPTOR.LASTTIME
	from  MENSAJE M
    INNER JOIN USUARIO IDEMISSOR ON M.FK_IDEMISSOR= IDEMISSOR.ID
	INNER JOIN USUARIO IDRECEPTOR ON M.FK_IDRECEPTOR = IDRECEPTOR.ID;
/**********************************************************************/
CREATE VIEW V_MIEMBRODELEQUIPO AS
SELECT
EU.FK_IDEQUIPO AS IDEQUIPO, EU.FK_IDUSUARIO AS IDUSUARIO, E.FK_IDCREADOR AS IDCREADOR, E.NOMBRE, E.IMAGEN
FROM 
EQUIPO E 
INNER join EQUIPOUSUARIOS EU ON EU.FK_IDEQUIPO = E.ID;
/**********************************************************************/
CREATE VIEW V_PUBLICACIONES_SHOWALLINFO AS
SELECT
P.HORA AS HORA, P.PUBLICACION AS PUBLICACION, P.EQUIPO AS EQUIPO, C.AVATAR AS AVATAR, C.NOMBRE AS NOMBRE
FROM PUBLICACIONES P 
INNER JOIN USUARIO C ON C.ID = P.FK_IDCREADOR;
/**********************************************************************/

CREATE VIEW V_TAREAS AS 
SELECT 
T.ID AS IDTAREA, T.TAREA AS TITULO, T.DESCRIPCION, UT.COMPLETADO, UT.FK_IDALUMNO AS ALUMNO
FROM USUARIOTAREA UT
INNER JOIN TAREAS T ON T.ID = UT.FK_IDTAREA;



