CREATE database POI;
Use  POI;

create table USUARIO(
ID	INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
AVATAR MEDIUMBLOB,
NOMBRE varchar(25),
USUARIO VARCHAR (50), 
CORREO VARCHAR(50),
PW varchar(25),
ACTIVO BOOL DEFAULT 1
);

CREATE table EQUIPO(
ID	INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOMBRE varchar(25),
ACTIVO BOOL DEFAULT 1

);

create table EQUIPOUSUARIOS(
ID	INT PRIMARY KEY NOT NULL AUTO_INCREMENT

);

Create table PUBLICACIONES(
ID	INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
PUBLICACION VARCHAR(500),
IMAGE BLOB,
HORA time,
ACTIVO BOOL DEFAULT 1
);

create table EQUIPOPUBLICACIONES(
ID	INT PRIMARY KEY NOT NULL AUTO_INCREMENT

);

Create table REGISTROLLAMADAS(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
DURACION TIME
);

Create table MENSAJE(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
MENSAJE VARCHAR(500),
HORA TIME,
VISTO BOOL,
IMAGEN BLOB
);

Create table TAREAS(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
TAREA VARCHAR(150)
);

CREATE TABLE USUARIOTAREA(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
COMPLETADO BOOL
);

ALTER TABLE EQUIPO
ADD FK_IDCREADOR INT,
ADD foreign key (FK_IDCREADOR) REFERENCES USUARIO(ID);

ALTER TABLE EQUIPOUSUARIOS
ADD FK_IDUSUARIO INT,
ADD foreign key (FK_IDUSUARIO) REFERENCES USUARIO(ID), 
ADD FK_IDEQUIPO INT,
ADD foreign key (FK_IDEQUIPO) REFERENCES EQUIPO(ID);

ALTER TABLE EQUIPOPUBLICACIONES
ADD FK_IDPUBLICACION INT,
ADD foreign key (FK_IDPUBLICACION) REFERENCES PUBLICACIONES(ID), 
ADD FK_IDEQUIPO INT,
ADD foreign key (FK_IDEQUIPO) REFERENCES EQUIPO(ID);

ALTER TABLE PUBLICACIONES
ADD FK_IDCREADOR INT, 
ADD foreign key (FK_IDCREADOR) REFERENCES USUARIO(ID);

ALTER TABLE MENSAJE
ADD FK_IDRECEPTOR INT, 
ADD foreign key (FK_IDRECEPTOR) REFERENCES USUARIO(ID), 
ADD FK_IDEMISSOR INT, 
ADD foreign key (FK_IDEMISSOR) REFERENCES USUARIO(ID);

ALTER TABLE TAREAS
ADD FK_IDCREADOR INT, 
ADD foreign key (FK_IDCREADOR) REFERENCES USUARIO(ID);

ALTER TABLE USUARIOTAREA
ADD FK_IDALUMNO INT,
ADD foreign key (FK_IDALUMNO) REFERENCES USUARIO(ID),
ADD FK_IDTAREA INT,
ADD foreign key (FK_IDTAREA) REFERENCES TAREAS(ID);


